name: Mark Submission on Issue Comment

on:
    workflow_dispatch:
    issue_comment:
        types: [created]

permissions:
    issues: write
    contents: write
    actions: read

jobs:
    call-mark-submission:
        uses: HUTECH-BMTT/workflow-templates/.github/workflows/mark-submission.yaml@main
        secrets: inherit
