name: Prevent Direct Push to Main

on:
  push:
    branches:
      - main

jobs:
  prevent-direct-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository với toàn bộ lịch sử commit
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch toàn bộ commit history

      # Thực hiện ngăn chặn direct push
      - name: Prevent push to main
        if: github.event_name == 'push' && github.event.head_commit.message != 'Merge pull request'
        run: |
          echo "Direct push to the main branch is not allowed. Your push will be reverted."
          git reset --hard HEAD~1
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git
          git push --force origin HEAD:main
          exit 1
