name: Process Students CSV

# Trigger workflow when there are any changes in the directory containing CSV files
on:
  push:
    branches:
      - main
    paths:
      - 'resources/students.csv' # Only trigger when any CSV file changes in the main branch

jobs:
  process-csv:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      # Run the main script
      - name: Run main.py
        env:
          GIT_FULL_ACCESS_TOKEN: ${{ secrets.GIT_FULL_ACCESS_TOKEN }}
        run: |
          python src/main.py
