name: Process Students CSV

# Trigger workflow khi có bất kỳ thay đổi trong thư mục chứa CSV files
on:
  push:
    paths:
      - 'students.csv' # Chỉ trigger khi file students.csv thay đổi

jobs:
  process-csv:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the main script
      - name: Run main.py
        env:
          GIT_FULL_ACCESS_TOKEN: ${{ secrets.GIT_FULL_ACCESS_TOKEN }}
        run: |
          python main.py
